version: "3.9"

services:
  euclid-elasticsearch:
    container_name: euclid-elasticsearch
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  euclid-kibana:
    container_name: euclid-kibana
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - euclid-elasticsearch
    networks:
      - elastic      

  euclid-backend: 
    container_name: euclid-backend 
    build: ./euclid 
    

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
